### ISSUE TITLE
Try to find better class names

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Primitives#3]
The Pr* naming scheme isn't that beautiful, we should find a new scheme and also check method names.

We can't simply remove the Pr Prefix if we want to avoid problems with `java.lang` wrapper classes. We also shouldn't just remove it where possible to keep a pattern throughout our api.

**Comment by deletescape** [comment]
For now I will remove the Pr prefix on array classes

**Comment by deletescape** [comment]
An option would just be to use plural forms like Longs or Bytes
